version: '3.7'

networks:
  bridge:
    external:
      name: ${NETWORKS}

services:
  malaysia-spring:
    image: nginx:alpine
    container_name: 0verMalaysiaSpring
    restart: unless-stopped
    tty: true
    environment:
      - TZ=Asia/Taipei
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./app/dist/:/usr/share/nginx/html/malaysia_spring/
    networks:
      - bridge
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.malaysia-spring.entrypoints=websecure"
      - "traefik.http.routers.malaysia-spring.tls.certresolver=lets-encr"
      - "traefik.http.routers.malaysia-spring.rule=Host(`${DOMAIN_NAME}`) && PathPrefix(`/malaysia_spring`)"
      - "traefik.http.routers.malaysia-spring.tls.options=default"
      - "traefik.http.routers.malaysia-spring.middlewares=secure-headers@file"